sudo: required
services:
  - docker

before_install:
  - docker build -t lhmcdev/fribonati-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lhmcdev/fribonati-docker-test npm test -- --coverage

after_success:
  - docker build -t lhmcdev/fribonati-docker-multi-client ./client
  - docker build -t lhmcdev/fribonati-docker-multi-nginx ./nginx
  - docker build -t lhmcdev/fribonati-docker-multi-server ./server
  - docker build -t lhmcdev/fribonati-docker-multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lhmcdev/fribonati-docker-multi-client
  - docker push lhmcdev/fribonati-docker-multi-nginx
  - docker push lhmcdev/fribonati-docker-multi-server
  - docker push lhmcdev/fribonati-docker-multi-worker